version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-step
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/github.com/calendar-open/
    environment:
      - GOOGLE_CALENDAR_ID
      - GOOGLE_API_CREDENTIAL
      - ADMIN_TOKEN
    ports:
      - 3002:8080
