name: Testing
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.13'
      - run: go test ./...

